# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      - run: npm install

      # run tests!
      - run: npm run test-ci
